spring:
  application:
    name: Cognitio
  datasource:
    url: jdbc:postgresql://localhost:5432/cognitio
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080


#Security

